package cloud.quierescomprar.model;

// Generated 22/07/2012 10:45:08 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "bd_quequierescomprar_empresa")
public class Empresa implements java.io.Serializable {

	private short CEmpresa;
	private String ruc;
	private String razonSocial;
	private Set<Oferta> ofertas = new HashSet<Oferta>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	

	public Empresa() {
	}

	public Empresa(short CEmpresa, String ruc, String razonSocial) {
		this.CEmpresa = CEmpresa;
		this.ruc = ruc;
		this.razonSocial = razonSocial;
	}

	public Empresa(short CEmpresa, String ruc, String razonSocial,
			Set<Oferta> ofertas, Set<Usuario> usuarios) {
		this.CEmpresa = CEmpresa;
		this.ruc = ruc;
		this.razonSocial = razonSocial;
		this.ofertas = ofertas;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "C_EMPRESA", unique = true, nullable = false)
	public short getCEmpresa() {
		return this.CEmpresa;
	}

	public void setCEmpresa(short CEmpresa) {
		this.CEmpresa = CEmpresa;
	}

	@Column(name = "RUC", nullable = false, length = 11)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "RAZON_SOCIAL", nullable = false, length = 100)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Oferta> getOfertas() {
		return this.ofertas;
	}

	public void setOfertas(Set<Oferta> ofertas) {
		this.ofertas = ofertas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
