package cloud.quierescomprar.model;

// Generated 22/07/2012 10:45:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OfertaVentaId generated by hbm2java
 */
@Embeddable
public class OfertaVentaId implements java.io.Serializable {

	private short CEmpresa;
	private String COferta;
	private short linea;

	public OfertaVentaId() {
	}

	public OfertaVentaId(short CEmpresa, String COferta, short linea) {
		this.CEmpresa = CEmpresa;
		this.COferta = COferta;
		this.linea = linea;
	}

	@Column(name = "C_EMPRESA", nullable = false)
	public short getCEmpresa() {
		return this.CEmpresa;
	}

	public void setCEmpresa(short CEmpresa) {
		this.CEmpresa = CEmpresa;
	}

	@Column(name = "C_OFERTA", nullable = false, length = 6)
	public String getCOferta() {
		return this.COferta;
	}

	public void setCOferta(String COferta) {
		this.COferta = COferta;
	}

	@Column(name = "LINEA", nullable = false)
	public short getLinea() {
		return this.linea;
	}

	public void setLinea(short linea) {
		this.linea = linea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OfertaVentaId))
			return false;
		OfertaVentaId castOther = (OfertaVentaId) other;

		return (this.getCEmpresa() == castOther.getCEmpresa())
				&& ((this.getCOferta() == castOther.getCOferta()) || (this
						.getCOferta() != null && castOther.getCOferta() != null && this
						.getCOferta().equals(castOther.getCOferta())))
				&& (this.getLinea() == castOther.getLinea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCEmpresa();
		result = 37 * result
				+ (getCOferta() == null ? 0 : this.getCOferta().hashCode());
		result = 37 * result + this.getLinea();
		return result;
	}

}
