package cloud.quierescomprar.model;

// Generated 08/07/2012 01:07:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oferta generated by hbm2java
 */
@Entity
@Table(name = "oferta", catalog = "bd_quierescomprar_ws")
public class Oferta implements java.io.Serializable {

	private Integer codOfe;
	private Producto producto;
	private Date fecIniOfe;
	private Date fecFinOfe;
	private Double porOfe;
	private String flgAct;
	
	

	public Oferta() {
	}

	public Oferta(Producto producto) {
		this.producto = producto;
	}

	
	public Oferta(Producto producto, Date fecIniOfe, Date fecFinOfe,
			Double porOfe, String flgAct) {
		this.producto = producto;
		this.fecIniOfe = fecIniOfe;
		this.fecFinOfe = fecFinOfe;
		this.porOfe = porOfe;
		this.flgAct=flgAct;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codOfe", unique = true, nullable = false)
	public Integer getCodOfe() {
		return this.codOfe;
	}

	public void setCodOfe(Integer codOfe) {
		this.codOfe = codOfe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codPro", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecIniOfe", length = 10)
	public Date getFecIniOfe() {
		return this.fecIniOfe;
	}

	public void setFecIniOfe(Date fecIniOfe) {
		this.fecIniOfe = fecIniOfe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecFinOfe", length = 10)
	public Date getFecFinOfe() {
		return this.fecFinOfe;
	}

	public void setFecFinOfe(Date fecFinOfe) {
		this.fecFinOfe = fecFinOfe;
	}

	@Column(name = "porOfe", precision = 22, scale = 0)
	public Double getPorOfe() {
		return this.porOfe;
	}

	public void setPorOfe(Double porOfe) {
		this.porOfe = porOfe;
	}
	
	
	@Column(name = "flgAct" , length = 1)
	public String getFlgAct() {
		return flgAct;
	}

	public void setFlgAct(String flgAct) {
		this.flgAct = flgAct;
	}

}
