package cloud.quierescomprar.model;

// Generated 22/07/2012 08:18:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oferta generated by hbm2java
 */
@Entity
@Table(name = "oferta", catalog = "bd_quequierescomprar_empresa")
public class Oferta implements java.io.Serializable {

	private OfertaId id;
	private Empresa empresa;
	private String descripcion;
	private BigDecimal precio;
	private BigDecimal descuento;
	private Date fechaInicio;
	private Date fechaFin;
	private String debeSaber;
	private String destacado;
	private String detalle;
	private String urlImagen;
	private Set<OfertaVenta> ofertaVentas = new HashSet<OfertaVenta>(0);

	public Oferta() {
	}

	public Oferta(OfertaId id, Empresa empresa, String descripcion,
			BigDecimal precio, BigDecimal descuento, Date fechaInicio,
			Date fechaFin) {
		this.id = id;
		this.empresa = empresa;
		this.descripcion = descripcion;
		this.precio = precio;
		this.descuento = descuento;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Oferta(OfertaId id, Empresa empresa, String descripcion,
			BigDecimal precio, BigDecimal descuento, Date fechaInicio,
			Date fechaFin, String debeSaber, String destacado, String detalle,
			String urlImagen, Set<OfertaVenta> ofertaVentas) {
		this.id = id;
		this.empresa = empresa;
		this.descripcion = descripcion;
		this.precio = precio;
		this.descuento = descuento;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.debeSaber = debeSaber;
		this.destacado = destacado;
		this.detalle = detalle;
		this.urlImagen = urlImagen;
		this.ofertaVentas = ofertaVentas;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "CEmpresa", column = @Column(name = "C_EMPRESA", nullable = false)),
			@AttributeOverride(name = "COferta", column = @Column(name = "C_OFERTA", nullable = false, length = 6)) })
	public OfertaId getId() {
		return this.id;
	}

	public void setId(OfertaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_EMPRESA", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "DESCRIPCION", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "PRECIO", nullable = false, precision = 10, scale = 3)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "DESCUENTO", nullable = false, precision = 10)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", nullable = false, length = 19)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", nullable = false, length = 19)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "DEBE_SABER", length = 65535)
	public String getDebeSaber() {
		return this.debeSaber;
	}

	public void setDebeSaber(String debeSaber) {
		this.debeSaber = debeSaber;
	}

	@Column(name = "DESTACADO", length = 65535)
	public String getDestacado() {
		return this.destacado;
	}

	public void setDestacado(String destacado) {
		this.destacado = destacado;
	}

	@Column(name = "DETALLE", length = 65535)
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "URL_IMAGEN")
	public String getUrlImagen() {
		return this.urlImagen;
	}

	public void setUrlImagen(String urlImagen) {
		this.urlImagen = urlImagen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oferta")
	public Set<OfertaVenta> getOfertaVentas() {
		return this.ofertaVentas;
	}

	public void setOfertaVentas(Set<OfertaVenta> ofertaVentas) {
		this.ofertaVentas = ofertaVentas;
	}

}
