package cloud.quierescomprar.model;

// Generated 22/07/2012 08:18:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OfertaVentaId generated by hbm2java
 */
@Embeddable
public class OfertaVentaId implements java.io.Serializable {

	private String COferta;
	private short linea;
	private String emailUsuario;
	private short CEmpresa;

	public OfertaVentaId() {
	}

	public OfertaVentaId(String COferta, short linea, String emailUsuario,
			short CEmpresa) {
		this.COferta = COferta;
		this.linea = linea;
		this.emailUsuario = emailUsuario;
		this.CEmpresa = CEmpresa;
	}

	@Column(name = "C_OFERTA", nullable = false, length = 6)
	public String getCOferta() {
		return this.COferta;
	}

	public void setCOferta(String COferta) {
		this.COferta = COferta;
	}

	@Column(name = "LINEA", nullable = false)
	public short getLinea() {
		return this.linea;
	}

	public void setLinea(short linea) {
		this.linea = linea;
	}

	@Column(name = "EMAIL_USUARIO", nullable = false, length = 40)
	public String getEmailUsuario() {
		return this.emailUsuario;
	}

	public void setEmailUsuario(String emailUsuario) {
		this.emailUsuario = emailUsuario;
	}

	@Column(name = "C_EMPRESA", nullable = false)
	public short getCEmpresa() {
		return this.CEmpresa;
	}

	public void setCEmpresa(short CEmpresa) {
		this.CEmpresa = CEmpresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OfertaVentaId))
			return false;
		OfertaVentaId castOther = (OfertaVentaId) other;

		return ((this.getCOferta() == castOther.getCOferta()) || (this
				.getCOferta() != null && castOther.getCOferta() != null && this
				.getCOferta().equals(castOther.getCOferta())))
				&& (this.getLinea() == castOther.getLinea())
				&& ((this.getEmailUsuario() == castOther.getEmailUsuario()) || (this
						.getEmailUsuario() != null
						&& castOther.getEmailUsuario() != null && this
						.getEmailUsuario().equals(castOther.getEmailUsuario())))
				&& (this.getCEmpresa() == castOther.getCEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCOferta() == null ? 0 : this.getCOferta().hashCode());
		result = 37 * result + this.getLinea();
		result = 37
				* result
				+ (getEmailUsuario() == null ? 0 : this.getEmailUsuario()
						.hashCode());
		result = 37 * result + this.getCEmpresa();
		return result;
	}

}
