package cloud.quierescomprar.model;

// Generated 08/07/2012 01:07:49 PM by Hibernate Tools 3.4.0.CR1


import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;


import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.Table;



/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "bd_quierescomprar_ws")
public class Producto implements java.io.Serializable {

	private Integer codPro;
	private String desPro;
	private Double prePro;
	//private Set<Oferta> ofertas;// = new HashSet<Oferta>(0);

	public Producto() {
	}

	public Producto(String desPro, Double prePro, Set<Oferta> ofertas) {
		this.desPro = desPro;
		this.prePro = prePro;
		//this.ofertas = ofertas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codPro", unique = true, nullable = false)
	public Integer getCodPro() {
		return this.codPro;
	}

	public void setCodPro(Integer codPro) {
		this.codPro = codPro;
	}

	@Column(name = "desPro", length = 45)
	public String getDesPro() {
		return this.desPro;
	}

	public void setDesPro(String desPro) {
		this.desPro = desPro;
	}

	@Column(name = "prePro", precision = 22, scale = 0)
	public Double getPrePro() {
		return this.prePro;
	}

	public void setPrePro(Double prePro) {
		this.prePro = prePro;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	
	public Set<Oferta> getOfertas() {
		return this.ofertas;
	}

	public void setOfertas(Set<Oferta> ofertas) {
		this.ofertas = ofertas;
	}
	*/
	/*
	@Transient
	public List<Oferta> getOfertasList() {
		return new ArrayList<Oferta>(ofertas);
	}
	*/

}
